version: '3.3'
services:
  db:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  pgadmin:
    image: 'dpage/pgadmin4:4.18'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '5050:80'
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin'
    links:
      - 'db:pgsql-server'
volumes:
  db-data: null
  pgadmin-data: null
