version: '3.3'
services:
  sql:
    image: 'mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04'
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: myStrongPassword123
    volumes:
      - 'sql-data:/var/opt/mssql'
    ports:
      - '1433:1433'
volumes:
  sql-data:
# docker exec -it <name> bash
# sqlcmd -S 10.3.2.4 -U SA -P '<YourPassword>'
